#pragma once

namespace ObjID
{
	enum ID { BOSS, BOSS_ARM, PLAYER, CLOTH, WEAPON, MONSTER, GOLD, BULLET, BULLET_BOSS, EFFECT, EFFECT_DAMAGE, UI, MAINUI, DROPITEM, EQUIPMENT, INVENTORY, MOUSE, END };
}